### PR TITLE
feat(template): support object style templates

### PR DESCRIPTION
**Pull request by jd-solanki**
### Description

We already have `template` function but we can't name the template variables for readability.

### Linked Issues

N/A

### Additional context

Thanks for this package ❤️

### CODE REVIEW

**Comment by antfu** [comment]
Maybe we could override the `template`?

**Comment by jd-solanki** [comment]
You mean, removing existing implementation? I wanted that 😅  but it might break your other package so I created new one.

Do you want to replace the existing template function with this one? I'll be happy to do that.

**Comment by jd-solanki** [comment]
Or you mean method & type overriding? Single function but does both 🤔

**Comment by antfu** [comment]
> Or you mean method & type overriding? Single function but does both 🤔

Yes :)

**Comment by jd-solanki** [comment]
> > Or you mean method & type overriding? Single function but does both 🤔
> 
> Yes :)

ohk, I'll try to implement that 👍🏻

**Pull request merged**
